### ISSUE TITLE
[sub-pause] Rebinding key only works when sent to all clients (script can't be targeted)

### ISSUE THREAD

**Issue by lionslancer** [Ben-Kerman/mpv-sub-scripts#10]
Trying to rebind the `sub-pause-toggle-end` in `input.conf` only works when sent to all clients.

These work:
`N script-binding sub-pause-toggle-end`
`N script-message sub-pause-toggle-end`

These do not:
`N script-binding sub-pause/sub-pause-toggle-end`
`N script-message-to sub-pause sub-pause-toggle-end`

While I think it's quite unlikely that any other script would have a function specifically named `sub-pause-toggle-end`, it would probably still be good practice to implement support for this in order to prevent name conflicts.

**Comment by Ben-Kerman** [comment]
You need to use `sub_pause/...`. mpv replaces all non-ASCII-alphanumeric characters with `_` when generating the script ID (cf. [player/scripting.c](https://github.com/mpv-player/mpv/blob/c1568a3a6c61252d5fc003602f00c0264a196822/player/scripting.c#L63)).

I added an explanation to the readme

**Comment by lionslancer** [comment]
I see, my mistake then. Thanks for teaching me something new anyhow!
