### ISSUE TITLE
Feature request: resume after X seconds in auto-pause

### ISSUE THREAD

**Issue by cocowash** [Ben-Kerman/mpv-sub-scripts#12]
Hi, I really like the idea to auto pause my videos so I have the time to read the translation. Nonetheless, I think that it would be nice if I could set that after X amount of time the video could continue automatically.

**Comment by TingTingin** [comment]
I second this it would be a good feature

**Comment by Ben-Kerman** [comment]
Added with 5c99106, see the readme for details

**Comment by cocowash** [comment]
@Ben-Kerman 
Hi, I have one question, it is intended that for applying the unpause_override the user needs to press twice the key when unpause_time is on? 
If I set the timer to 0 I can unpause just pressing space bar just once, otherwise I need to press it twice in order to work. Could it be possible to unpause as well with just one key press instead of two? 
Btw, Ty for your hard work.
