### ISSUE TITLE
Doesn't Stop Playback

### ISSUE THREAD

**Issue by JayXT** [Ben-Kerman/mpv-sub-scripts#14]
Hello,
It looks like the script doesn't work with mpv 0.32.0. Occasionally it stops the playback, but in most cases there's no effect, despite availability of subtitles and activation of pausing functionality using "n" shortcut.
OS: Debian 11.

**Comment by Ben-Kerman** [comment]
Update to a more recent version of mpv. 0.32 was released in January 2020 and these scripts no longer work with it since February 2022

If you're ok with using an older version, b2ebcce should still be compatible with 0.32 (or 8be0f21 if that doesn't work)
