### ISSUE TITLE
Replay Last Sub

### ISSUE THREAD

**Issue by CE-Yazeed** [Ben-Kerman/mpv-sub-scripts#17]
A heavenly feature would be replay last, any chance that'd be added? I tried doing it myself quickly but wouldn't function

**Comment by Ben-Kerman** [comment]
Can't you already do that by default with `Ctrl+←`? I personally never felt the need for anything more involved than that and the replay shortcut that's already part of sub-pause

**Comment by mrfragger** [comment]
Alt+e  no-osd sub-seek 0                            #! [Subtitles] > [Navigation] > Replay Current Subtitle

but most likely one will wait till next sub starts so wishes to replay the sub just before the current one
Ctrl+LEFT   no-osd sub-seek -1                              #! [Subtitles] > [Navigation] > Previous Subtitle
