### ISSUE TITLE
Potplayer support?

### ISSUE THREAD

**Issue by 4Brad-23** [Ben-Kerman/mpv-sub-scripts#23]

**Comment by Ben-Kerman** [comment]
I've never heard about that player before, but not happening, for several reasons:
- PotPlayer seems to be proprietary and Windows-exclusive. I only use Linux and generally prefer open-source software
- It's completely unrelated to mpv and doesn't even seem to use Lua as a scripting language, so you'd have to rewrite these scripts from scratch anyway
- I can't find any documentation on how extensions work for it (not that it matters anyway, for above reasons)
