### ISSUE TITLE
Add an option for 'sub-pause' to pause at the start of a line (instead of just the end).

### ISSUE THREAD

**Issue by Lucridius** [Ben-Kerman/mpv-sub-scripts#6]
It'd be nice if you were able to have the option to video pause at the start of the subtitles instead of just the end.

(and maybe even, have it pause at the start and end (though I'm not sure if anyone would use that))

Anyway great work :D

**Comment by Ben-Kerman** [comment]
Implemented.
You can now assign a custom key binding for toggling pausing at the start of lines as per the readme.
