### ISSUE TITLE
the seek part of the sub-skip doesn't seem to work 

### ISSUE THREAD

**Issue by Joa35235235** [Ben-Kerman/mpv-sub-scripts#9]
it fast-forwards to the next subtitle when I press ctrl+n, but when I press ctrl+alt+n nothing happens

**Comment by Ben-Kerman** [comment]
It works perfectly for me, even without any cache and practically no muxer read-ahead.

Did you turn on skipping? `sub-skip-switch-mode` only changes how the script skips, it doesn't activate it.

**Comment by Joa35235235** [comment]
oh, I didn't realize the seeking part was only a mode to the script itself. Sorry to waste your time, and thanks for the script!
